import Item1 from "../../images/item1.jpg";
import Item2 from "../../images/item2.jpg";
import Item3 from "../../images/item3.jpg";
import Item4 from "../../images/item4.jpg";
import Item5 from "../../images/item5.jpg";
import Item6 from "../../images/item6.jpg";
import Item7 from "../../images/item7.jpg";
import Item8 from "../../images/item8.jpg";
import Item9 from "../../images/item9.jpg";

export const obj = {
  arr: [
    {
      id: 1,
      img: Item1,
      name: "product 1",
      inStock: true,
      delivery: "fast",
      price: 10,
      rating: 1.8,
      title: "Winter body Sneakers",
    },
    {
      id: 2,
      img: Item2,
      name: "product 2",
      inStock: false,
      delivery: "standard",
      price: 20,
      rating: 2.6,
      title: "Adidas Windbreaker",
    },
    {
      id: 3,
      img: Item3,
      name: "product 3",
      inStock: true,
      delivery: "fast",
      price: 10000,
      rating: 3.7,
      title: "Vans 404s",
    },
    {
      id: 4,
      img: Item4,
      name: "product 4",
      inStock: false,
      delivery: "standard",
      price: 40,
      rating: 4.6,
      title: "Yeezy's White sneakers",
    },
    {
      id: 5,
      img: Item5,
      name: "product 5",
      inStock: true,
      delivery: "standard",
      price: 5000,
      rating: 2.9,
      title: "Cropped-sho sneakers",
    },
    {
      id: 6,
      img: Item6,
      name: "product 6",
      inStock: false,
      delivery: "fast",
      price: 9,
      rating: 1.8,
      title: "Blues",
    },
    {
      id: 7,
      img: Item7,
      name: "product 7",
      inStock: false,
      delivery: "fast",
      price: 659,
      rating: 1.8,
      title: "Coffee",
    },
    {
      id: 8,
      img: Item8,
      name: "product 8",
      inStock: false,
      delivery: "fast",
      price: 889,
      rating: 1.8,
      title: "Sunglasses",
    },
    {
      id: 9,
      img: Item9,
      name: "product 9",
      inStock: false,
      delivery: "fast",
      price: 229,
      rating: 1.8,
      title: "Camera",
    },
    {
      id: 10,
      img: Item1,
      name: "product 1",
      inStock: true,
      delivery: "fast",
      price: 180,
      rating: 1.8,
      title: "Winter body Sneakers",
    },
    {
      id: 11,
      img: Item2,
      name: "product 2",
      inStock: false,
      delivery: "standard",
      price: 230,
      rating: 2.6,
      title: "Adidas Windbreaker",
    },
    {
      id: 12,
      img: Item3,
      name: "product 3",
      inStock: true,
      delivery: "fast",
      price: 2000,
      rating: 3.7,
      title: "Vans 404s",
    },
    {
      id: 13,
      img: Item4,
      name: "product 4",
      inStock: false,
      delivery: "standard",
      price: 420,
      rating: 4.6,
      title: "Yeezy's White sneakers",
    },
    {
      id: 14,
      img: Item5,
      name: "product 5",
      inStock: true,
      delivery: "standard",
      price: 100,
      rating: 2.9,
      title: "Cropped-sho sneakers",
    },
    {
      id: 15,
      img: Item6,
      name: "product 6",
      inStock: false,
      delivery: "fast",
      price: 329,
      rating: 1.8,
      title: "Blues",
    },
    {
      id: 16,
      img: Item7,
      name: "product 7",
      inStock: false,
      delivery: "fast",
      price: 759,
      rating: 1.8,
      title: "Coffee",
    },
    {
      id: 17,
      img: Item8,
      name: "product 8",
      inStock: false,
      delivery: "fast",
      price: 89,
      rating: 1.8,
      title: "Sunglasses",
    },
    {
      id: 18,
      img: Item9,
      name: "product 9",
      inStock: false,
      delivery: "fast",
      price: 119,
      rating: 1.8,
      title: "Camera",
    },
  ],
};
