export const autoCompleteData = [
  "Shirts",
  "Casual Shirts for Men",
  "Formal Shirts for Men",
  " Hoodies for Men",
  "Cotton Shirts for Men",
  "T Shirts for Men ",
  "Polo T shirts",
  "Kurta Pajama for Men",
  " White Shirt",
  " Black Shirt",
  "Lower for Men",
  " Jeans for Men ",
  "Kurta Payjama Sets",
  " Kurta for Men ",
  "Blazer for Men ",
  "Sweater for Men",
  "Tops for Women",
  "Kurti",
  "Cotton Sarees ",
  "Georgette Sarees ",
  "Jumpsuit for Women ",
  "Jeans for Women",
  "Salwar Suit",
  "Bra",
  "Jacket for Women",
  "Night Dress for Women ",
  "Sweatshirt for Women ",
  "Shorts for Women",
  "Readymade Blouse",
  "Dupatta",
  "Shirts for Women ",
  "Skirts for Women ",
  "Ethnic wear for Women",
  "Western Dresses for Women",
  " Leggings for Women",
  "Men's Footwear",
  "Casual Shoes for Men",
  "Formal Shoes for Men",
  "Slippers",
  "Boots",
  "Sandals for Men ",
  "Footwear for Women ",
  "Heels for Women ",
  "Sandals for Women",
  "Shoes for Women",
  "Sandals for Women",
  "Slippers for Women",
  "Boots for Women",
  "Jutti for",
  "Women",
  "Sports Shoes for Women",
  "Home & Kitchen",
  "Wall Painting",
  " Wall Stickers ",
  "Dream Catcher ",
  "Clock",
  "Wall",
  "Clock",
  "Diya",
  "Bean Bag ",
  " Laptop Table ",
  "Study Table",
  " Wall Hanging",
  "Ceiling Lights ",
  " Table Lamp ",
  "Hanging Lights ",
  " LED Bulbs",
  " Torch Light",
  "LED Lights",
  "Flower Vase ",
  "Keychain",
  "Rudraksha",
  "Screwdriver",
  "Watch",
  "Watch For Men",
  "Womens Watches ",
  "Smart Watch",
  "Girls",
  "Home Furnishing: Bed Sheet",
  " Mosquito Net ",
  "Mattress",
  "Cover",
  "Blanket",
  "Pillow",
  "Quilt",
  "Pillow Cover",
  "Electronics: Bluetooth Speakers",
  "Headphones",
  "Earphone",
  "Geysers",
  "Trimmer",
  "Straightner",
  "Hair",
  "Dryer",
  " Water Purifier",
  " Mixer Grinder ",
  " Gas Stove",
  "Electric Kettle",
  "Mobiles Accessories: Mobile Covers",
  "Leather Mobile Covers",
  "Covers",
  "Tempered",
];
